### ISSUE TITLE
Where can I get the model 'C3D_small_PyTorch_Trained_12.pth'?

### ISSUE THREAD

**Issue by MALLLLLLL** [ParitoshParmar/MTL-AQA#3]
Where can I get the model 'C3D_small_PyTorch_Trained_12.pth'?

**Comment by ParitoshParmar** [comment]
@MALLLLLLL : I have uploaded the pretrained model here: https://github.com/ParitoshParmar/MTL-AQA/tree/master/MTL-AQA_code_release/models/MSCADC/pretrained_models/. Please use 7-zip to uncompress.
